#!/bin/bash -l
#SBATCH --time=24:00:00
#SBATCH --job-name=download_era
#SBATCH --gres=gpu:1

# Environment variables
export MPLBACKEND="agg"
conda activate pyart-2021
cd /lcrc/group/earthscience/rjackson/opencrums/scripts
python download_era5_conus_500mb.py
