#!/bin/bash -l
#SBATCH -N 1        
#SBATCH --time=24:00:00
#SBATCH --job-name=train_encoder
#SBATCH -n 1
#SBATCH --gres=gpu:1
# Environment variables

export MPLBACKEND="agg"
conda activate pydda_env
cd /lcrc/group/earthscience/rjackson/opencrums/scripts
python train_multi_encoder_optimized.py BCCMASS
python train_multi_encoder_optimized.py BCFLUXU
python train_multi_encoder_optimized.py BCFLUXV
python train_multi_encoder_optimized.py BCSMASS
python train_multi_encoder_optimized.py DMSCMASS
python train_multi_encoder_optimized.py DMSSMASS
python train_multi_encoder_optimized.py DUCMASS
python train_multi_encoder_optimized.py DUCMASS25
python train_multi_encoder_optimized.py DUFLUXU
python train_multi_encoder_optimized.py DUFLUXV
python train_multi_encoder_optimized.py DUSMASS
python train_multi_encoder_optimized.py DUSMASS25
python train_multi_encoder_optimized.py OCCMASS
python train_multi_encoder_optimized.py OCFLUXU
python train_multi_encoder_optimized.py OCFLUXV
python train_multi_encoder_optimized.py OCSMASS
python train_multi_encoder_optimized.py SO2CMASS
python train_multi_encoder_optimized.py SO2SMASS
python train_multi_encoder_optimized.py SO4CMASS
python train_multi_encoder_optimized.py SO4SMASS
python train_multi_encoder_optimized.py SSCMASS
python train_multi_encoder_optimized.py SSCMASS25
python train_multi_encoder_optimized.py SSFLUXU
python train_multi_encoder_optimized.py SSFLUXV
python train_multi_encoder_optimized.py SSSMASS
python train_multi_encoder_optimized.py SSSMASS25
python train_multi_encoder_optimized.py SUFLUXU
python train_multi_encoder_optimized.py SUFLUXV
